#[oath2]
secrets_file = "/Users/gm/Documents/python_scripts/gdrive/config/client_secrets.json"
settings_file = "/Users/gm/Documents/python_scripts/gdrive/config/settings.yaml"
save_credentials_file = "/Users/gm/Documents/python_scripts/gdrive/config/credentials.json"

#[files]
file_type = "zip"
# This is an id of your Google Drive folder
folder_id = "1fTJ1L1FfjP5E1Y-AJMCJOkV3amqEJj3-"