#[oath2]
secrets_file = "/Users/gm/Documents/python_scripts/gdrive/config/client_secrets.json"
settings_file = "/Users/gm/Documents/python_scripts/gdrive/config/settings.yaml"
save_credentials_file = "/Users/gm/Documents/python_scripts/gdrive/config/credentials.json"

#[files]
work_dir = "/Users/gm/Downloads/"
file_type = "zip"
folder_id = "1iTJ1Q7FfjP5E1Y-AJMCJOkV3amqEHj3c"