client_config_backend: settings
client_config:
  client_id: 84935237255-fk6xj948v8lt9au1dlrnktm7k0n33k1.apps.googleusercontent.com
  client_secret: POCSQR-YL97JO3ZkcCZhD-YyaLNPlKYWbOA

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.file